In [7]:
#INSTALL LIBRARIES
!pip install pandas numpy matplotlib

Requirement already satisfied: pandas in c:\users\baman\anaconda3\lib\site-packages (2.0.3)
Requirement already satisfied: numpy in c:\users\baman\anaconda3\lib\site-packages (1.24.3)
Requirement already satisfied: matplotlib in c:\users\baman\anaconda3\lib\site-packages (3.7.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\baman\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\baman\anaconda3\lib\site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\baman\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\baman\anaconda3\lib\site-packages (from matplotlib) (1.0.5)
Requirement already satisfied: cycler>=0.10 in c:\users\baman\anaconda3\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\baman\anaconda3\lib\site-packages (from matplotlib) (4.25.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\baman\anaconda3\lib\site-packages (from matplotlib) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\baman\anaconda3\lib\site-packages (from matplotlib) (23.1)
Requirement already satisfied: pillow>=6.2.0 in c:\users\baman\anaconda3\lib\site-packages (from matplotlib) (9.4.0)
Requirement already satisfied: pyparsing<3.1,>=2.3.1 in c:\users\baman\anaconda3\lib\site-packages (from matplotlib) (3.0.9)
Requirement already satisfied: six>=1.5 in c:\users\baman\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [8]:
#IMPORT LIBRARIES
import pandas as pd
import numpy as np

In [9]:
#LOAD CSV FILES
matches=pd.read_csv(r"C:\Users\baman\OneDrive\Desktop\IPL\matches.csv")
deliveries=pd.read_csv(r"C:\Users\baman\OneDrive\Desktop\IPL\deliveries.csv")

In [10]:
#VIEW DATA
matches.head()

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,18-04-2008,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,19-04-2008,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,19-04-2008,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,20-04-2008,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,20-04-2008,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111,20.0,N,NaN,BF Bowden,K Hariharan

In [11]:
##VIEW DATA
deliveries.head()

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN

In [12]:
#CHECK DATA INFO
matches.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1095 non-null   int64
 1   season           1095 non-null   object
 2   city             1044 non-null   object
 3   date             1095 non-null   object
 4   match_type       1095 non-null   object
 5   player_of_match  1090 non-null   object
 6   venue            1095 non-null   object
 7   team1            1095 non-null   object
 8   team2            1095 non-null   object
 9   toss_winner      1095 non-null   object
 10  toss_decision    1095 non-null   object
 11  winner           1090 non-null   object
 12  result           1095 non-null   object
 13  result_margin    1076 non-null   float64
 14  target_runs      1095 non-null   int64
 15  target_overs     1095 non-null   float64
 16  super_over       1095 non-null   object
 17  method           21 non-null     object
 18  umpire1          1095 non-null   object
 19  umpire2          1095 non-null   object
dtypes: float64(2), int64(2), object(16)
memory usage: 171.2+ KB

In [13]:
#CHECK DATA INFO
deliveries.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260920 entries, 0 to 260919
Data columns (total 17 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   match_id          260920 non-null  int64
 1   inning            260920 non-null  int64
 2   batting_team      260920 non-null  object
 3   bowling_team      260920 non-null  object
 4   over              260920 non-null  int64
 5   ball              260920 non-null  int64
 6   batter            260920 non-null  object
 7   bowler            260920 non-null  object
 8   non_striker       260920 non-null  object
 9   batsman_runs      260920 non-null  int64
 10  extra_runs        260920 non-null  int64
 11  total_runs        260920 non-null  int64
 12  extras_type       14125 non-null   object
 13  is_wicket         260920 non-null  int64
 14  player_dismissed  12950 non-null   object
 15  dismissal_kind    12950 non-null   object
 16  fielder           9354 non-null    object
dtypes: int64(8), object(9)
memory usage: 33.8+ MB

In [14]:
#CHECK NULL VALUES
matches.isnull().sum()

id                    0
season                0
city                 51
date                  0
match_type            0
player_of_match       5
venue                 0
team1                 0
team2                 0
toss_winner           0
toss_decision         0
winner                5
result                0
result_margin        19
target_runs           0
target_overs          0
super_over            0
method             1074
umpire1               0
umpire2               0
dtype: int64

In [15]:
#HANDLE NULL VALUES
matches['city']=matches['city'].fillna("Unknown")
matches['player_of_match']=matches['player_of_match'].fillna("No Award")
matches['winner']=matches['winner'].fillna("No Result")
matches['result_margin']=matches['result_margin'].fillna(0)
matches['method']=matches['method'].fillna("Normal")

matches.isnull().sum()

id                 0
season             0
city               0
date               0
match_type         0
player_of_match    0
venue              0
team1              0
team2              0
toss_winner        0
toss_decision      0
winner             0
result             0
result_margin      0
target_runs        0
target_overs       0
super_over         0
method             0
umpire1            0
umpire2            0
dtype: int64

In [16]:
#CHECK NULL VALUES
deliveries.isnull().sum()

match_id                 0
inning                   0
batting_team             0
bowling_team             0
over                     0
ball                     0
batter                   0
bowler                   0
non_striker              0
batsman_runs             0
extra_runs               0
total_runs               0
extras_type         246795
is_wicket                0
player_dismissed    247970
dismissal_kind      247970
fielder             251566
dtype: int64

In [17]:
#HANDLE NULL VALUES
deliveries['extras_type']=deliveries['extras_type'].fillna("Unknown")
deliveries['player_dismissed']=deliveries['player_dismissed'].fillna("Unknown")
deliveries['dismissal_kind']=deliveries['dismissal_kind'].fillna("Unknown")
deliveries['fielder']=deliveries['fielder'].fillna("Unknown")

deliveries.isnull().sum()

match_id            0
inning              0
batting_team        0
bowling_team        0
over                0
ball                0
batter              0
bowler              0
non_striker         0
batsman_runs        0
extra_runs          0
total_runs          0
extras_type         0
is_wicket           0
player_dismissed    0
dismissal_kind      0
fielder             0
dtype: int64

In [18]:
#CHECK DUPLICATES
matches.duplicated().sum()

np.int64(0)

In [19]:
#CHECK DUPLICATES
deliveries.duplicated().sum()

np.int64(0)

In [20]:
#REMOVE DUPLICATES(if needed)
matches.drop_duplicates(inplace=True)

In [21]:
#REMOVE DUPLICATES(if needed)
deliveries.drop_duplicates(inplace=True)

In [22]:
# Standardizing team names to maintain consistency in analysis
# Delhi Daredevils renamed to Delhi Capitals
# Kings XI Punjab renamed to Punjab Kings

matches.replace({
    'Delhi Daredevils':'Delhi Capitals',
    'Kings XI Punjab':'Punjab Kings'
},inplace=True)

deliveries.replace({
    'Delhi Daredevils':'Delhi Capitals',
    'Kings XI Punjab':'Punjab Kings'
},inplace=True)

In [23]:
# Verifying standardized team names in matches dataset
'Delhi Daredevils' in matches['team1'].unique()

False

In [24]:
# Verifying standardized team names in matches dataset
'Delhi Daredevils' in matches['team2'].unique()

False

In [25]:
# Verifying standardized team names in matches dataset
'Kings XI Punjab' in matches['team1'].unique()

False

In [26]:
# Verifying standardized team names in matches dataset
'Kings XI Punjab' in matches['team2'].unique()

False

In [27]:
#CHECK UNIQUE TEAM1 NAMES
matches['team1'].unique()

array(['Royal Challengers Bangalore', 'Punjab Kings', 'Delhi Capitals',
       'Mumbai Indians', 'Kolkata Knight Riders', 'Rajasthan Royals',
       'Deccan Chargers', 'Chennai Super Kings', 'Kochi Tuskers Kerala',
       'Pune Warriors', 'Sunrisers Hyderabad', 'Gujarat Lions',
       'Rising Pune Supergiants', 'Rising Pune Supergiant',
       'Lucknow Super Giants', 'Gujarat Titans',
       'Royal Challengers Bengaluru'], dtype=object)

In [28]:
#CHECK UNIQUE TEAM2 NAMES
matches['team2'].unique()

array(['Kolkata Knight Riders', 'Chennai Super Kings', 'Rajasthan Royals',
       'Royal Challengers Bangalore', 'Deccan Chargers', 'Punjab Kings',
       'Delhi Capitals', 'Mumbai Indians', 'Kochi Tuskers Kerala',
       'Pune Warriors', 'Sunrisers Hyderabad', 'Rising Pune Supergiants',
       'Gujarat Lions', 'Rising Pune Supergiant', 'Gujarat Titans',
       'Lucknow Super Giants', 'Royal Challengers Bengaluru'],
      dtype=object)

In [29]:
# Verifying standardized batting team names in deliveries dataset
deliveries['batting_team'].unique()

array(['Kolkata Knight Riders', 'Royal Challengers Bangalore',
       'Chennai Super Kings', 'Punjab Kings', 'Rajasthan Royals',
       'Delhi Capitals', 'Mumbai Indians', 'Deccan Chargers',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Sunrisers Hyderabad',
       'Rising Pune Supergiants', 'Gujarat Lions',
       'Rising Pune Supergiant', 'Lucknow Super Giants', 'Gujarat Titans',
       'Royal Challengers Bengaluru'], dtype=object)

In [30]:
# Verifying standardized batting team names in deliveries dataset
deliveries['bowling_team'].unique()

array(['Royal Challengers Bangalore', 'Kolkata Knight Riders',
       'Punjab Kings', 'Chennai Super Kings', 'Delhi Capitals',
       'Rajasthan Royals', 'Mumbai Indians', 'Deccan Chargers',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Sunrisers Hyderabad',
       'Rising Pune Supergiants', 'Gujarat Lions',
       'Rising Pune Supergiant', 'Gujarat Titans', 'Lucknow Super Giants',
       'Royal Challengers Bengaluru'], dtype=object)

In [31]:
# Standardizing remaining inconsistent team names
matches.replace({
    'Royal Challengers Bangalore':'Royal Challengers Bengaluru',
    'Rising Pune Supergiants':'Rising Pune Supergiant'
}, inplace=True)

deliveries.replace({
    'Royal Challengers Bangalore':'Royal Challengers Bengaluru',
    'Rising Pune Supergiants':'Rising Pune Supergiant'
}, inplace=True)

In [32]:
# Verifying updated team names after standardization
matches['team1'].unique()
matches['team2'].unique()

deliveries['batting_team'].unique()
deliveries['bowling_team'].unique()

array(['Royal Challengers Bengaluru', 'Kolkata Knight Riders',
       'Punjab Kings', 'Chennai Super Kings', 'Delhi Capitals',
       'Rajasthan Royals', 'Mumbai Indians', 'Deccan Chargers',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Sunrisers Hyderabad',
       'Rising Pune Supergiant', 'Gujarat Lions', 'Gujarat Titans',
       'Lucknow Super Giants'], dtype=object)

In [33]:
# Converting date column into proper datetime format
matches['date']=pd.to_datetime(matches['date'],dayfirst=True)

In [34]:
# Displaying first few rows of date column after conversion
matches['date'].head()

0   2008-04-18
1   2008-04-19
2   2008-04-19
3   2008-04-20
4   2008-04-20
Name: date, dtype: datetime64[ns]

In [35]:
# Creating a new column for match year
matches['year']=matches['date'].dt.year

In [36]:
# Displaying date and extracted year columns
matches[['date','year']].head()

        date  year
0 2008-04-18  2008
1 2008-04-19  2008
2 2008-04-19  2008
3 2008-04-20  2008
4 2008-04-20  2008

In [37]:
# Creating match phase categories based on overs
def over_phase(over):
    if over<=5:
        return 'Powerplay'
    elif over<=15:
        return 'Middle Overs'
    else:
        return 'Death Overs'
deliveries['phase']=deliveries['over'].apply(over_phase)

In [38]:
# Displaying over and phase columns
deliveries[['over','phase']].head()

   over      phase
0     0  Powerplay
1     0  Powerplay
2     0  Powerplay
3     0  Powerplay
4     0  Powerplay

In [39]:
# Creating boundary indicator column (4s and 6s)
deliveries['is_boundary']=deliveries['batsman_runs'].apply(
    lambda x:1 if x in [4,6] else 0
)

In [40]:
# Displaying batsman runs and boundary indicator
deliveries[['batsman_runs','is_boundary']].head(15)

    batsman_runs  is_boundary
0              0            0
1              0            0
2              0            0
3              0            0
4              0            0
5              0            0
6              0            0
7              0            0
8              4            1
9              4            1
10             6            1
11             4            1
12             0            0
13             0            0
14             0            0

In [41]:
# Creating four indicator column
deliveries['is_four']=deliveries['batsman_runs'].apply(
    lambda x:1 if x==4 else 0
)
# Displaying batsman runs and four indicator
deliveries[['batsman_runs','is_four']].head(20)

    batsman_runs  is_four
0              0        0
1              0        0
2              0        0
3              0        0
4              0        0
5              0        0
6              0        0
7              0        0
8              4        1
9              4        1
10             6        0
11             4        1
12             0        0
13             0        0
14             0        0
15             0        0
16             4        1
17             1        0
18             0        0
19             0        0

In [42]:
# Creating six indicator column
deliveries['is_six']=deliveries['batsman_runs'].apply(
    lambda x:1 if x==6 else 0
)
# Displaying batsman runs and six indicator
deliveries[['batsman_runs','is_six']].head(20)

    batsman_runs  is_six
0              0       0
1              0       0
2              0       0
3              0       0
4              0       0
5              0       0
6              0       0
7              0       0
8              4       0
9              4       0
10             6       1
11             4       0
12             0       0
13             0       0
14             0       0
15             0       0
16             4       0
17             1       0
18             0       0
19             0       0

In [43]:
# Creating dot ball indicator column
deliveries['is_dot']=deliveries['batsman_runs'].apply(
    lambda x:1 if x in [0] else 0
)

In [44]:
# Displaying total runs and dot ball indicator
deliveries[['batsman_runs','is_dot']].head(10)

   batsman_runs  is_dot
0             0       1
1             0       1
2             0       1
3             0       1
4             0       1
5             0       1
6             0       1
7             0       1
8             4       0
9             4       0

In [45]:
# Displaying unique dismissal types line by line
for dismissal in deliveries['dismissal_kind'].unique():
    print(dismissal)

Unknown
caught
bowled
run out
lbw
retired hurt
stumped
caught and bowled
hit wicket
obstructing the field
retired out

In [46]:
# Creating bowler wicket indicator column
deliveries['bowler_wicket']=deliveries['dismissal_kind'].apply(
    lambda x:1
    if x in[
        'bowled',
        'caught',
        'caught and bowled',
        'lbw',
        'stumped',
        'hit wicket'
    ]
    else 0
)

In [47]:
# Displaying dismissal kind and bowler wicket indicator
deliveries[['dismissal_kind','bowler_wicket']].head(100)

   dismissal_kind  bowler_wicket
0         Unknown              0
1         Unknown              0
2         Unknown              0
3         Unknown              0
4         Unknown              0
..            ...            ...
95        Unknown              0
96        Unknown              0
97        Unknown              0
98        Unknown              0
99        Unknown              0

[100 rows x 2 columns]

In [48]:
# Counting bowler wickets
deliveries['bowler_wicket'].value_counts()

bowler_wicket
0    249105
1     11815
Name: count, dtype: int64

In [49]:
#VERIFY CLEAN DATA
# Checking null values in matches dataset
matches.isnull().sum()
# Checking null values in deliveries dataset
deliveries.isnull().sum()

match_id            0
inning              0
batting_team        0
bowling_team        0
over                0
ball                0
batter              0
bowler              0
non_striker         0
batsman_runs        0
extra_runs          0
total_runs          0
extras_type         0
is_wicket           0
player_dismissed    0
dismissal_kind      0
fielder             0
phase               0
is_boundary         0
is_four             0
is_six              0
is_dot              0
bowler_wicket       0
dtype: int64

In [50]:
#CHECK NEW COLUMNS
# Displaying first few rows of matches dataset
matches.head()
# Displaying first few rows of deliveries dataset
deliveries.head()

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,...,is_wicket,player_dismissed,dismissal_kind,fielder,phase,is_boundary,is_four,is_six,is_dot,bowler_wicket
0,335982,1,Kolkata Knight Riders,Royal Challengers Bengaluru,0,1,SC Ganguly,P Kumar,BB McCullum,0,...,0,Unknown,Unknown,Unknown,Powerplay,0,0,0,1,0
1,335982,1,Kolkata Knight Riders,Royal Challengers Bengaluru,0,2,BB McCullum,P Kumar,SC Ganguly,0,...,0,Unknown,Unknown,Unknown,Powerplay,0,0,0,1,0
2,335982,1,Kolkata Knight Riders,Royal Challengers Bengaluru,0,3,BB McCullum,P Kumar,SC Ganguly,0,...,0,Unknown,Unknown,Unknown,Powerplay,0,0,0,1,0
3,335982,1,Kolkata Knight Riders,Royal Challengers Bengaluru,0,4,BB McCullum,P Kumar,SC Ganguly,0,...,0,Unknown,Unknown,Unknown,Powerplay,0,0,0,1,0
4,335982,1,Kolkata Knight Riders,Royal Challengers Bengaluru,0,5,BB McCullum,P Kumar,SC Ganguly,0,...,0,Unknown,Unknown,Unknown,Powerplay,0,0,0,1,0

In [51]:
# Exporting cleaned matches dataset into CSV file
matches.to_csv("cleaned_matches.csv", index=False)

# Exporting cleaned deliveries dataset into CSV file
deliveries.to_csv("cleaned_deliveries.csv", index=False)

In [52]:
# Reading exported cleaned matches dataset
cleaned_matches = pd.read_csv("cleaned_matches.csv")

# Reading exported cleaned deliveries dataset
cleaned_deliveries = pd.read_csv("cleaned_deliveries.csv")

In [53]:
# Displaying first few rows of exported cleaned matches dataset
cleaned_matches.head()

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,...,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2,year
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bengaluru,Kolkata Knight Riders,Royal Challengers Bengaluru,...,Kolkata Knight Riders,runs,140.0,223,20.0,N,Normal,Asad Rauf,RE Koertzen,2008
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Punjab Kings,Chennai Super Kings,Chennai Super Kings,...,Chennai Super Kings,runs,33.0,241,20.0,N,Normal,MR Benson,SL Shastri,2008
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Capitals,Rajasthan Royals,Rajasthan Royals,...,Delhi Capitals,wickets,9.0,130,20.0,N,Normal,Aleem Dar,GA Pratapkumar,2008
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bengaluru,Mumbai Indians,...,Royal Challengers Bengaluru,wickets,5.0,166,20.0,N,Normal,SJ Davis,DJ Harper,2008
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,...,Kolkata Knight Riders,wickets,5.0,111,20.0,N,Normal,BF Bowden,K Hariharan,2008

In [54]:
# Displaying first few rows of exported cleaned deliveries dataset
cleaned_deliveries.head()

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,...,is_wicket,player_dismissed,dismissal_kind,fielder,phase,is_boundary,is_four,is_six,is_dot,bowler_wicket
0,335982,1,Kolkata Knight Riders,Royal Challengers Bengaluru,0,1,SC Ganguly,P Kumar,BB McCullum,0,...,0,Unknown,Unknown,Unknown,Powerplay,0,0,0,1,0
1,335982,1,Kolkata Knight Riders,Royal Challengers Bengaluru,0,2,BB McCullum,P Kumar,SC Ganguly,0,...,0,Unknown,Unknown,Unknown,Powerplay,0,0,0,1,0
2,335982,1,Kolkata Knight Riders,Royal Challengers Bengaluru,0,3,BB McCullum,P Kumar,SC Ganguly,0,...,0,Unknown,Unknown,Unknown,Powerplay,0,0,0,1,0
3,335982,1,Kolkata Knight Riders,Royal Challengers Bengaluru,0,4,BB McCullum,P Kumar,SC Ganguly,0,...,0,Unknown,Unknown,Unknown,Powerplay,0,0,0,1,0
4,335982,1,Kolkata Knight Riders,Royal Challengers Bengaluru,0,5,BB McCullum,P Kumar,SC Ganguly,0,...,0,Unknown,Unknown,Unknown,Powerplay,0,0,0,1,0